blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('blog/', views.blog, name='blog'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_detail, name='cart_detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
	path('order/', views.order, name='order'),
	path('succefull/', views.succefull, name='succefull'),
	path('order/send/', views.OrderSendView.as_view(), name='ordersend'),
]

shop/urls.py
from django.urls import path, include
from . import views
from .views import *


app_name = 'shop'


urlpatterns = [
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('', views.index, name='index'),
    path('shop/', views.shop, name='shop'),
    path('my_account/', views.my_account, name='my_account'),
    # path('shopping/', views.shopping, name='shopping'),
    path('checkout/', views.checkout, name='checkout'),
    path('contact/', views.contact, name='contact'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('detail/', views.detail, name='detail'),
    path('blog/', views.blog, name='blog'),
    path('applications/', views.ApplicationsView.as_view(), name='applications'),
    # path('shop2/', views.listing, name='listing')
    # path('shop/', views.ShopListView.as_view(), name='shop'),
    # path('<slug:category_slug>/', views.shopping, name='product_list_by_category'),
    # path('<int:id>/<slug:slug>/', views.product_details, name='product_detail'),
]

webshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 100)]

class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label=_('Quantity'))
	update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

class OrderSendForm(forms.Form):
    name = forms.CharField()
    phone = forms.CharField()
    mail = forms.CharField(required=False)	

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm, OrderSendForm
import telebot 
from django.views import View


bot = telebot.TeleBot("1260971143:AAEVskAqdKb_rMMBfST-4WwQsqeOtNiu9Og")

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                            'update': True})
    return render(request, 'cart/cart.html', {'cart': cart})

def order(request):
    return render(request, 'cart/create.html')

def succefull(request):
    return render(request, 'cart/created.html')

class OrderSendView(View):
    def post(self, request):
        if request.method == 'POST':
            form = OrderSendForm(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                phone = form.cleaned_data['phone']
                if form.cleaned_data['mail'] == '':
                    mail = 'Не указана'
                else:
                    mail = form.cleaned_data['mail']
                cart = Cart(request)
                message = 'Поступил новый заказ!\r\n\r\nИмя: ' + name + '\r\nТелефон: ' + phone + '\r\nПочта: ' \
                          + mail + '\r\n\r\nПродукты\r\n\r\n'

                for c in cart:
                    message += 'Название: ' + str(c['product']) + '\r\n'
                    message += 'Цена: ' + str(c['price']) + '\r\n\r\n'
                    message += 'Количество: ' + str(c['quantity']) + '\r\n\r\n'

                message += 'Общая стоимость: ' + str(cart.get_total_price())

                bot.send_message(-481287996, message)
                Cart.clear(cart)
                return redirect('cart:succefull')
            return redirect('shop:shop')    

cart/templates/cart/cart.html
{% extends 'shop/index.html' %}
{% load static %}

 {% block title %}<title>Shopping-Cart</title>{% endblock %}

{% block content %}
		<div class="cart-main-area">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="entry-header">
							<h1 class="entry-title">Shopping cart</h1>
						</div>
						<div class="table-content">
							
								<div class="table-content table-responsive">
									<table>
										<thead>
											<tr>
												<th class="product-thumbnail">Image</th>
												<th class="product-name">Product</th>
												<th class="product-price">Price</th>
												<th class="product-quantity">Quantity</th>
												<th class="product-subtotal">Total</th>
												<th class="product-remove">Remove</th>
											</tr>
										</thead>
										<tbody>
										{% for item in cart %}
                                        	{% with product=item.product %}
											<tr>
												<td class="product-thumbnail">
													<a href="">
														<img src="{{ product.image.url }}" alt="" />
													</a>
												</td>
												<td class="product-name">
													<a href="{% url 'shop:shop' %}">{{ product.name }}</a>
												</td>
												<td class="product-price">
													<span class="amount">{{ product.price }}</span>
												</td>
												<td class="product-quantity">
													<form action="{% url 'cart:cart_add' product.id %}" method="POST">
														{{ item.update_quantity_form.quantity }}
														{{ item.update_quantity_form.update }}
														<input type="submit" value="Update">
														{% csrf_token %}
													</form>
												</td>
												<td class="product-subtotal">
													{{ item.total_price }}
												</td>
												<td class="product-remove">
													<a href="{% url 'cart:cart_remove' product.id %}">
													  remove
													</a>
												</td>
											</tr>
											{% endwith %}
										{% endfor %}
										</tbody>
									</table>
								</div>
								<div class="row">
									</div>
									<div class="wc-proceed-to-checkout">
												<a href="{% url 'shop:shop' %}" class="button">
													Back to shop
												</a>
											</div>
									<div class="col-md-4">
										<div class="cart_totals">
											<h2>Cart Totals</h2>
											<table>
												{% for sum in cart %}
             									{% with product=sum.product %}
												<tbody>
													<tr class="cart-subtotal">
														<th>Subtotal</th>
														<td>
															<span class="amount">{{ product.price }}</span>
														</td>
													</tr>
													
													<tr class="order-total">
														<th>Total</th>
														<td>
															<strong>
																<span class="amount">{{ cart.get_total_price }}</span>
															</strong>
														</td>
													</tr>
												</tbody>
												{% endwith %}
            									{% endfor %}
											</table>
											<div class="wc-proceed-to-checkout">
												<a href="{% url 'cart:order' %}" class="button">
													Checkout
												</a>
											
										</div>
									</div>
								</div>
						
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- shopping-cart-end -->
		
		<!-- footer-start -->
{% endblock %}

cart/templates/cart/create.html
{% extends "shop/index.html" %}
{% load static %}

{% block content %}
<h1>Checkout</h1>
<div class="order-info">
<h3>Your order</h3>
<ul>
{% for item in cart %}
<li>
{{ item.quantity }}x {{ item.product.name }}
<span>${{ item.total_price }}</span>
</li>
{% endfor %}
</ul>
<p>Total: ${{ cart.get_total_price }}</p>
</div>
<div class="checkout-wrap pt-30">
                    <div class="row">
                        <div class="col-lg-7">
                            <form action="{% url 'cart:ordersend' %}" method="POST">
                            <div class="billing-info-wrap mr-50">
                                <h3>Заполните форму</h3>
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-6 col-md-6">
                                        <div class="billing-info mb-20">
                                            <label>Имя </label>
                                            <input name="name" type="text">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6">
                                        <div class="billing-info mb-20">
                                            <label>Номер телефона </label>
                                            <input name="phone" type="text">
                                        </div>
                                    </div>
                                 
                                </div>
                                <div class="checkout-account-toggle open-toggle2 mb-30">
                                    <label>Электронная почта</label>
                                    <input placeholder="example@gmail.com" name="mail">
                                </div>
                                <div class="col-md-12">
                                    <input type="submit" class="btn btn-main btn-block" value="Подтвердить заказ">
                                </div>
                            </div>
                            </form>
                        </div>
                        </div>
                        </div>	
{% endblock %}

cart/templates/cart/created.html
{% extends "shop/index.html" %}
{% block title %}
Thank you
{% endblock %}

{% block content %}
<h1>Thank you</h1>
<p>Your order has been successfully completed. Your order number is
<strong>{{ order.id }}</strong>.</p>
{% endblock %}

cart/templates/cart/details.html
{% extends 'shop/index.html' %}
{% load static %}


{% block title %}<title>Home three || Vonia</title>{% endblock %}
{% block content %}
		<!-- header-end -->
		<!-- product-details-area-start -->
		<div class="shop-1-area">
			<div class="container">
				<div class="breadcrumb">
					<a href="{% url 'shop:index' %}" title="Return to Home">
						<i class="icon-home"></i>
					</a>
					<span class="navigation-pipe">></span>
					<span class="navigation-page">
						<a href="product-details.html" title="Furniture ">
							<span>Furniture </span>
						</a>
						<span class="navigation-pipe nav-pipe-2">></span>
						Faded Short Sleeves T-shirt
					</span>
				</div>
				<div class="row">
					<div class="col-md-5 col-sm-6 col-xs-12">
						<div class="picture-tab">
                            <!-- Nav tabs -->
                            <ul class="pic-tabs" role="tablist">
    							<li role="presentation" class="active"><a href="product-details.html#picture-1" aria-controls="picture-1" role="tab" data-toggle="tab"><img src="http://preview.hasthemes.com/vonia-preview/vonia/img/tab-pro/1.jpg" alt="" /></a></li>
							    <li role="presentation"><a href="product-details.html#picture-2" aria-controls="picture-2" role="tab" data-toggle="tab"><img src="http://preview.hasthemes.com/vonia-preview/vonia/img/tab-pro/2.jpg" alt="" /></a></li>
							    <li role="presentation"><a href="product-details.html#picture-3" aria-controls="picture-3" role="tab" data-toggle="tab"><img src="http://preview.hasthemes.com/vonia-preview/vonia/img/tab-pro/3.jpg" alt="" /></a></li>
							    <li role="presentation"><a href="product-details.html#picture-4" aria-controls="picture-4" role="tab" data-toggle="tab"><img src="http://preview.hasthemes.com/vonia-preview/vonia/img/tab-pro/5.jpg" alt="" /></a></li>
                            </ul>
                            <div class="tab-content">
								<div role="tabpanel" class="tab-pane active fade in" id="picture-1">
									<div class="single-product">
										<div class="product-img">
											<a href="product-details.html">
												<img src="img/tab-pro/faded-short-sleeves-tshirt.jpg" alt="" />
											</a>
											<span class="new">new</span>
											<span class="sale">sale!</span>
										</div>
									</div>
								</div>
								<div role="tabpanel" class="tab-pane fade" id="picture-2">
									<div class="single-product">
										<div class="product-img">
											<a href="product-details.html">
												<img src="img/tab-pro/lamp2.jpg" alt="" />
											</a>
											<span class="new">new</span>
											<span class="sale">sale!</span>
										</div>
									</div>
								</div>
								<div role="tabpanel" class="tab-pane fade" id="picture-3">
									<div class="single-product">
										<div class="product-img">
											<a href="product-details.html">
												<img src="img/tab-pro/lamp.jpg" alt="" />
											</a>
											<span class="new">new</span>
											<span class="sale">sale!</span>
										</div>
									</div>
								</div>
								<div role="tabpanel" class="tab-pane fade" id="picture-4">
									<div class="single-product">
										<div class="product-img">
											<a href="product-details.html">
												<img src="{% static 'img/tab-pro/vass.jpg' %}" alt="" />
											</a>
											<span class="new">new</span>
											<span class="sale">sale!</span>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-7 col-sm-6 col-xs-12 shop-content">
						<h1>Faded Short Sleeves T-shirt</h1>
						<p class="reference">
							<label>Reference: </label>
							<span>demo_1</span>
						</p>
						<p class="condition">
							<label>Condition: </label>
							<span>New product</span>
						</p>
						<div class="content-price">
							<p class="price-new">
								<span class="price-box">£ 16.84</span>
								<span class="price-tax"> tax incl.</span>
							</p>
							<p class="reduction-percent">
								<span>-15%</span>
							</p>
							<p class="old-price">
								<span class="price">£ 19.81</span>
								tax incl.
							</p>
						</div>
						<div class="short-description">
							<p>Faded short sleeves t-shirt with high neckline. Soft and stretchy material for a comfortable fit. 
							Accessorize with a straw hat and you're ready for summer!
							</p>
						</div>
						<form action="product-details.html">
							<div class="shop-product-add">
								<div class="add-cart">
									<p class="quantity cart-plus-minus">
										<label>Quantity</label>
										<input class="text" type="text" value="1">
										
									</p>
									<div class="shop-add-cart">
										<button class="exclusive">
											<span>Add to cart</span>
										</button>
									</div>
									<ul class="usefull-links">
										<li class="sendtofriend">
											<a class="send-friend-button" href="product-details.html"> Send to a friend </a>
										</li>
										<li class="print">
											<a class="#" href="product-details.html"> Print </a>
										</li>
									</ul>
									<p class="add-wishlist">
										<a class="add-wish" href="product-details.html">
											 Add to wishlist 
										</a>
									</p>
								</div>
								<div class="clearfix"></div>
								<div class="size-color">
									<fieldset class="size">
										<label>Size </label>
										<div class="selector">
											<select id="group_1" class="form-control" name="group_1">
												<option title="S" selected="selected" value="1">S</option>
												<option title="M" value="2">M</option>
												<option title="L" value="3">L</option>
											</select>
										</div>
									</fieldset>
									<fieldset class="color">
										<label>Color</label>
										<div class="color-selector">
											<ul>
												<li><a class="color-1" href="product-details.html"></a></li>
												<li><a class="color-2" href="product-details.html"></a></li>
											</ul>
										</div>
									</fieldset>
								</div>
							</div>
						</form>
						<div class="clearfix"></div>
						<p class="quantity-available">
							<span>299</span>
							<span>Items</span>
						</p>
						<p class="availability-status">
							<span>In stock</span>
						</p>
						
						<div class="product-comment">
							<div class="comment-note clearfix">
								<span>Rating </span>
								<div class="star-content clearfix">
									<span class="star star-on"></span>
									<span class="star star-on"></span>
									<span class="star star-on"></span>
									<span class="star star-on"></span>
									<span class="star star-on"></span>
								</div>
							</div>
							<ul class="comments-advices">
								<li>
									<a class="reviews" href="product-details.html"> Read reviews (1)</a>									
								</li>
								<li>
									<a class="open-comment-form" href="product-details.html"> Write a review </a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- product-details-area-end -->
		
		
		<!-- footer-start -->
{% endblock %}