blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('blog/', views.blog, name='blog'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_detail, name='cart_detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
	path('order/', views.order, name='order'),
	path('succefull/', views.succefull, name='succefull'),
	path('order/send/', views.OrderSendView.as_view(), name='ordersend'),
]

shop/urls.py
from django.urls import path, include
from . import views
from .views import *


app_name = 'shop'


urlpatterns = [
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('', views.index, name='index'),
    path('shop/', views.shop, name='shop'),
    path('my_account/', views.my_account, name='my_account'),
    # path('shopping/', views.shopping, name='shopping'),
    path('checkout/', views.checkout, name='checkout'),
    path('contact/', views.contact, name='contact'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('detail/', views.detail, name='detail'),
    path('blog/', views.blog, name='blog'),
    path('applications/', views.ApplicationsView.as_view(), name='applications'),
    # path('shop2/', views.listing, name='listing')
    # path('shop/', views.ShopListView.as_view(), name='shop'),
    # path('<slug:category_slug>/', views.shopping, name='product_list_by_category'),
    # path('<int:id>/<slug:slug>/', views.product_details, name='product_detail'),
]

webshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime



class Blog(models.Model):
	title = models.CharField(max_length=20)
	img =models.ImageField(null=True, blank=True, upload_to='images/')
	describe= models.CharField(max_length=350)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.CharField(max_length=200)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    price2 = models.DecimalField(max_digits=10, decimal_places=3)
    stock = models.PositiveIntegerField() #delete
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name_plural = 'Shop'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])



class Applications(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=200)
    mail = models.CharField(verbose_name='Почта', max_length=200)
    comment = models.CharField(verbose_name='Коммент', max_length=200)
    date = models.DateTimeField(verbose_name='Дата', auto_now_add=True, null=True)

    def __str__(self):
        return self.mail

    class Meta:
        verbose_name = 'Заявка cо страницы контактов'
        verbose_name_plural = 'Заявка со страницы контактов'

shop/forms.py
from django import forms
from .models import Applications
from django.db import models


class ApplicationsForm(forms.ModelForm):
    class Meta:
        model = Applications
        fields = ['mail', 'name', 'comment']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from . models import Post



def blog(request):
    product = Product.objects.all()
    product_list = Product.objects.all()
    cart_product_form = CartAddProductForm()
    page = request.GET.get('page', 1)

    paginator = Paginator(product_list, 1)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    context = {'cart_product_form': cart_product_form, 
                'producent': product,
                'products': products,   
    }
    return render(request, 'blog/blog.html', context)

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from cart.forms import CartAddProductForm
from django.views import View
from blog.models import Blog
from django.core.mail import send_mail
import telebot
from .forms import ApplicationsForm
from django.views.generic import ListView
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


bot = telebot.TeleBot("1260971143:AAEVskAqdKb_rMMBfST-4WwQsqeOtNiu9Og")


def index(request):
    product = Product.objects.all()
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/index.html', {'product':product, 'cart_product_form':cart_product_form})


def my_account(request):
	return render(request, 'shop/account.html')

def shopping(request):
	return render(request, 'cart/shopping-cart.html')

def checkout(request):
	return render(request, 'shop/checkout.html')

def contact(request):
    form = ApplicationsForm()
    return render(request, 'shop/contact.html', {'form': form})


def wishlist(request):
	return render(request, 'shop/wishlist.html')

def detail(request):
	return render(request, 'shop/product-details.html')			

def shop(request):
    product = Product.objects.all()
    product_list = Product.objects.all()
    cart_product_form = CartAddProductForm()
    page = request.GET.get('page', 1)

    paginator = Paginator(product_list, 3)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    context = {'cart_product_form': cart_product_form, 
                'producent': product,
                'products': products,   
    }
    return render(request, 'shop/shop.html', context)

def blog(request):
    blog = Blog.objects.all()
    context = {
        'blog': blog,
    }
    return render(request, 'blog/blog.html', context)



  

class ApplicationsView(View):
    def post(self, request):
        if request.method == 'POST':
            form = ApplicationsForm(request.POST)
            # print(request.POST)
        if form.is_valid():
            form.save()
            mail = form.cleaned_data['mail']
            name = form.cleaned_data['name']
            comment = form.cleaned_data['comment']
            subject = 'Новая заявка!'
            from_email = 'kiroskost@gmail.com'
            to_email = ['kiroskost@gmail.com', 'kirosbush@gmail.com']
            message = 'Новая заявка!' + '\r\n' + '\r\n' + 'Почта: ' + mail + '\r\n' + '\r\n' + 'Имя: ' + name + '\r\n' + 'Коммент: ' + comment
            send_mail(subject, message, from_email, to_email, fail_silently=False)
            bot.send_message(-481287996, message)
        return redirect('shop:contact')


class SearchResultsView(ListView):
    model = Product
    template_name = 'shop/search_results.html'
    
    def get_queryset(self): # новый
        query = self.request.GET.get('q')
        object_list = Product.objects.filter(
            Q(name__icontains=query) | Q(category__icontains=query)
        )
        return object_list


# def listing(request):
#     product = Product.objects.all()
#     product_list = Product.objects.all()
#     paginator = Paginator(product_list, 3) # Show 25 contacts per page.

#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)
#     return render(request, 'shop/shop.html', {'page_obj': page_obj, 'producent':product})

shop/templates/shop/contact.html
{% extends 'shop/index.html' %}
{% load static %}
{% block title %}<title>Home three || Vonia</title>{% endblock %}

{% block content %}
		<!-- header-end -->
		<!-- contact-us-start -->
		<div class="contact-us-area">
			<div class="container">
				<div class="breadcrumb-area">
					<div class="container">
						<div class="breadcrumb">
							<a href="index.html" title="Return to Home">
								<i class="icon-home"></i>
							</a>
							<span class="navigation-pipe">></span>
							<span class="navigation-page">
								Contact
							</span>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="entry-header">
							<h1 class="entry-title">Customer service - Contact us</h1>
						</div>
						<form action="{% url 'shop:applications' %}" method="POST" >
								<div class="row">
									<div class="col-xs-12 col-md-3">
										{% csrf_token %}
										<div class="form-group">
											<label>Имя</label>
											<div class="shop-select">
												<input name="name" id="name">
											</div>											
										</div>
										<div class="form-group">
											<label>Электронная почта</label>
											<div class="shop-select">
												<input name="mail" id="email">
											</div>											
										</div>
									</div>
									<div class="col-xs-12 col-md-9">
											<div class="form-group">
												<label for="comment">Сообщение</label>
												<div class="shop-select">
												<textarea name="comment" id="message"></textarea>
												</div>											
											</div>										
									</div>

								</div>
								<!-- <input type="submit"> -->
								<div class="submit">
									<button class="button btn btn-default button-medium" type="submit">
										<span>
											send
											<i class="icon-chevron-right right"></i>
										</span>
									</button>
								</div>
						</form>
					</div>
				</div>
			</div>
		</div>
		<!-- contact-us-end -->
		
		<!-- footer-start -->
{% endblock %}		

shop/templates/shop/header.html
{% load static %}
<header class="header-3">
			<div class="header-top">
				<div class="container">
					<div class="row">
						<!-- <div class="col-md-6 col-sm-6 hidden-xs">
							
							<div class="currencies">
								<div class="current">
									<span class="cur-label">Currency :</span>
									<strong>KGS</strong>
								</div>
								<ul class="lan-cur">
									<li>
										<a href="index.html"> Dollar (USD) </a>
									</li>
									<li>
										<a href="index.html"> Som (KGS) </a>
									</li>
								</ul>
							</div>
						</div> -->
					<!-- 	<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="header-userinfo">
								<ul class="header-links"> -->
									<!-- <li class="first">
										<a class="link-myaccount" title="My account" href="{% url 'shop:my_account' %}"> My account </a>
									</li> -->
									<!-- <li>
										<a class="link-wishlist wishlist_block" title="My wishlist" href="{% url 'shop:wishlist' %}">My wishlist</a>
									</li>
									<li>
										<a class="link-checkout" title="checkout" href="{% url 'shop:checkout' %}">Checkout</a>
									</li> -->
								<!-- 	<li>
										<a class="login" title="Log in to your customer account" rel="nofollow" href="index.html">Log in</a>
									</li> -->
							<!-- 	</ul>
							</div>
						</div> -->
					</div>
				</div>
			</div>
			<div class="header-middle">
				<div class="container">
					<div class="row">
						<div class="col-md-4 col-sm-6 col-xs-12 hidden-xs">
							<div class="search-block-top">
								<form action="{% url 'shop:search_results' %}" method="get">
  									<input name='q' type="text" value="" placeholder="Поиск" >
								</form>
							</div>
						</div>
						<div class="col-md-4 col-sm-6 col-xs-12">
							<div class="pos-logo">
								<a href="index.html">
									<img class="logo img-responsive" src="{% static 'img/logo.jpg' %}" alt="" />
								</a>
							</div>
						</div>						
						<div class="col-md-4 col-sm-12 col-xs-12">
							<div class="shopping-cart">
								<a href="{% url 'cart:cart_detail' %}" rel="nofollow" title="View my shopping cart">
									<b>Корзина</b>
								</a>
							
						<div class="col-md-4 col-sm-6 col-xs-12 visible-xs">
							<div class="search-block-top">
								<input class="search-query-top" type="text" value="" placeholder="Search" >
								<button class="btn btn-default button-search" name="submit_search" type="submit"></button>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- header-middle-area-end -->
			<!-- mainmenu-area-start -->
			<div class="main-menu-area hidden-xs hidden-sm">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="main-menu">
								<nav>

									<ul>
										<li>
											<a  href="{% url 'shop:index' %}">Главная</a>
											
										</li>
										<li>
											<a  href="{% url 'shop:blog' %}">Блог</a>
											
										</li>
										<li>
											<a href="{% url 'shop:shop' %}">Магазин</a>
											
										</li>
										<!-- <li>
											<a href="{% url 'shop:detail' %}">Product details</a>
										</li> -->
										<!-- <li>
											<a href="{% url 'shop:wishlist' %}">Выбранные</a>
											
										</li> -->
										
									<!-- 	<li>
											
											<a href="{% url 'shop:my_account' %}">Аккаунт</a>
										</li>	 -->
												
										<li>
											<a href="{% url 'shop:contact' %}">Контакты</a>
										</li>	
												
										<!-- <li>
											<a href="{% url 'shop:checkout' %}">Проверка</a>
										</li> -->	
					                  </div>
										
									</ul>
								</nav>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- mainmenu-area-end -->
			<!-- mobile-menu-area-start -->
			<div class="mobile-menu-area visible-xs visible-sm">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="mobile_menu">
								<nav id="mobile_menu_active">
									<ul>
										<li><a href="index.html">Home</a>
											<ul>
												
										<li>
											<a  href="{% url 'shop:index' %}">Главная</a>
										</li>		
										<li>
											<a  href="{% url 'shop:blog' %}">Блог</a>
											
										</li>
										<li>
											<a href="{% url 'shop:shop' %}">Магазин</a>
											
										</li>
										
									<!-- 	<li>
											<a href="{% url 'shop:wishlist' %}">Выбранное</a>
											
										</li> -->
										
									<!-- 	<li>
											
											<a href="{% url 'shop:my_account' %}">Аккаунт</a>
										</li>	
												 -->
										<li>
											<a href="{% url 'shop:contact' %}">Контакты</a>
										</li>	
												
										<!-- <li>
											<a href="{% url 'shop:checkout' %}">Проверка</a>
										</li> -->	
										</ul>		
								</nav>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- mobile-menu-area-end -->
		</header>

shop/templates/shop/pagination.html
<!-- <div class="pagination">  
 <span class="step-links">  
  {% if page.has_previous %}  
      <a href="?page={{ page.previous_page_number }}">След.</a>  
  {% endif %}  
    <span class="current">  
  Page {{ page.number }} of {{ page.paginator.num_pages }}.  
    </span>  
  {% if page.has_next %}  
        <a href="?page={{ page.next_page_number }}">Пред.</a>  
  {% endif %}  
  </span>  
</div> -->


                        <div class="shop-pagination">
                            <div class="row">
                                <div class="col-md-6 col-xs-6">
                                    <div class="product-count">
                                        Showing 1 - 12 of 13 items
                                    </div>
                                    <ul class="pagination">
                                       {% if page_obj.has_previous %}
                                        <li class="pagination-previous-bottom">
                                            <a href="?page={{ page_obj.previous_page_number }}">
                                                <i class="fa fa-angle-left"></i>
                                            </a>
                                        </li>
                                        {% endif %}
                                        <li class="active current">
                                            <a href="shop.html">
                                                1
                                            </a>
                                        </li>
                                        <li>
                                            <a href="shop.html">
                                                2
                                            </a>
                                        </li>
                                         {% if page_obj.has_next %}
                                        <li class="pagination-next-bottom">
                                            <a href="page_obj.next_page_number">
                                                <i class="fa fa-angle-right"></i>
                                            </a>
                                        </li>
                                        {% endif %}
                                    </ul>
                                </div>
                                
                            </div>
                        </div>

shop/templates/shop/shop.html
{% extends 'shop/index.html' %}
{% load static %}
 {% block title %}<title>Home three || Vonia</title>{% endblock %}


{% block content %}
		
		<div class="shop-2-area">
			<div class="container">
				<div class="row">
					<div class="left-column col-sm-3">
						<div class="left-column-block">
							<h1>Каталог</h1>
							<div class="block-content">
								<div class="content-box">
									<h3 class="content-box-heading">
										Категории
									</h3>
									<ul>
										<li>
											<span class="checkit">
												<input class="checkbox" type="checkbox">
											</span>
											<label class="check-label">
												<a href="shop.html">Сумки (13)</a>
											</label>
										</li>
										<li>
											<span class="checkit">
												<input class="checkbox" type="checkbox">
											</span>
											<label class="check-label">
												<a href="shop.html">Футболки (13)</a>
											</label>
										</li>
										<li>
											<span class="checkit">
												<input class="checkbox" type="checkbox">
											</span>
											<label class="check-label">
												<a href="shop.html">Бельё (13)</a>
											</label>
										</li>
									</ul>
								</div>
								
								
								
								<div class="content-box">
									<h3 class="content-box-heading">Цена</h3>
									<div class="info_widget">
										<div class="price_filter">
											<div id="slider-range"></div>
												<div class="price_slider_amount">
												<input type="text" id="amount" name="price"  placeholder="Add Your Price" />
												<input type="submit"  value="Range"/>  
											</div>
										</div>
									</div>	
								</div>
								<div class="content-box">
									<h3 class="content-box-heading">Размер</h3>
									<ul>
										<li>
											<span class="checkit">
												<input class="checkbox" type="checkbox">
											</span>
											<label class="check-label">
												<a href="shop.html">S (13)</a>
											</label>
										</li>
										<li>
											<span class="checkit">
												<input class="checkbox" type="checkbox">
											</span>
											<label class="check-label">
												<a href="shop.html">L (13)</a>
											</label>
										</li>
										<li>
											<span class="checkit">
												<input class="checkbox" type="checkbox">
											</span>
											<label class="check-label">
												<a href="shop.html">M (13)</a>
											</label>
										</li>
									</ul>
								</div>
								<!-- <div class="content-box">
									<h3 class="content-box-heading">
										Color
									</h3>
									<ul>
										<li>
											<input class="color-option Beige" type="checkbox">
											<label class="check-label">
												<a href="shop.html">Бежевый (2)</a>
											</label>
										</li>
										<li>
											<input class="color-option white" type="checkbox">
											<label class="check-label">
												<a href="shop.html">Белый (4)</a>
											</label>
										</li>
										<li>
											<input class="color-option black" type="checkbox">
											<label class="check-label">
												<a href="shop.html">Черный (4)</a>
											</label>
										</li>
										<li>
											<input class="color-option orange" type="checkbox">
											<label class="check-label">
												<a href="shop.html">Оранжевый (5)</a>
											</label>
										</li>
										<li>
											<input class="color-option blue" type="checkbox">
											<label class="check-label">
												<a href="shop.html">Синий (3)</a>
											</label>
										</li>
										<li>
											<input class="color-option green" type="checkbox">
											<label class="check-label">
												<a href="shop.html">Зеленый (2)</a>
											</label>
										</li>
										<li>
											<input class="color-option yellow" type="checkbox">
											<label class="check-label">
												<a href="shop.html">Желтый (6)</a>
											</label>
										</li>
										<li>
											<input class="color-option pink" type="checkbox">
											<label class="check-label">
												<a href="shop.html">Розовый (2)</a>
											</label>
										</li>
									</ul>
								</div> -->
								<!-- <div class="content-box">
									<h3 class="content-box-heading">
										Материал
									</h3>
									<ul>
										<li>
											<span class="checkit">
												<input class="checkbox" type="checkbox">
											</span>
											<label class="check-label">
												<a href="shop.html">Хлопок (5)</a>
											</label>
										</li>
										<li>
											<span class="checkit">
												<input class="checkbox" type="checkbox">
											</span>
											<label class="check-label">
												<a href="shop.html">Полиэстер (4)</a>
											</label>
										</li>
										
									</ul>
								</div> -->
								<!-- <div class="content-box">
									<h3 class="content-box-heading">
										Стили
									</h3>
									<ul>
										<li>
											<span class="checkit">
												<input class="checkbox" type="checkbox">
											</span>
											<label class="check-label">
												<a href="shop.html">Повседневный (5)</a>
											</label>
										</li>
										<li>
											<span class="checkit">
												<input class="checkbox" type="checkbox">
											</span>
											<label class="check-label">
												<a href="shop.html"> Коктельный (2)</a>
											</label>
										</li>
										
									</ul>
								</div> -->
								
							</div>
						</div>
						
					</div>
					<div class="col-sm-9">
						
						<div class="shop-heading">
							<!-- <h2>bedding</h2> -->
							<!-- <span>13 товаров.</span> -->
						</div>
						<div class="clearfix"></div>
						<div class="category-products">
							
							<div class="shop-category-product">
								<div class="row">
									<div class="category-product">
										<!-- Tab panes -->
										
										<div class="tab-content">

											<div role="tabpanel" class="tab-pane active fade in" id="gried_view">
												{% for p in products %}
												<div class="col-md-4 col-sm-6 col-xs-12">
													<div class="single-product">
														<div class="product-img">
															<a href="shop.html">
																{% if p.image %}
																<img src="{{ p.image.url }}" alt="" />
																{% endif %}
															</a>
															<!-- <span class="new">{{  p.new }}</span>
															<span class="sale">{{  p.sale }}</span> -->
															<div class="product-action">
																<div class="add-to-links">
																	<ul>
																		<li>
																			<form action="{% url 'cart:cart_add' p.id %}" method="POST">
																			{% csrf_token %}
																			{{ cart_product_form }}
																			<input  type="submit" value="Добавить в корзину">

																			<!-- <a href="#" title="Add to cart">
																				<i class="fa fa-shopping-cart"></i>
																			</a> -->
																			</form>
																		</li>
																		<!-- <li>
																			<a href="{% url 'shop:wishlist' %}" title="Add to wishlist">
																				<i class="fa fa-heart" aria-hidden="true"></i>
																			</a>
																		</li> -->
																		<li>
																																					</li>
																	</ul>
																	<div class="quick-view">
																		<a target="_blank" href="{% url 'shop:detail' %}" data-toggle="modal" data-target="#myModal" title="Quick view">
																			<span>Подробно</span>
																		</a>
																	</div>
																</div>
															</div>
														</div>
														<div class="product-content">
															<h5 class="product-name">
																<a href="shop.html" title="Printed Chiffon Dress">{{ p.name }}</a>
															</h5>
															

															<div class="price-box">
																<span class="price">{{ p.price }} сом</span>
																<span class="old-price">{{ p.price2 }} сом</span>
															</div>
														</div>
													</div>
												</div>
											{% endfor %}
										</div>
										
									</div>
								</div>
							</div>
						</div>
							
									<!-- 	 <div class="shop-pagination">
                            <div class="row">
                                <div class="col-md-6 col-xs-6">
                                    <div class="product-count">
                                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                    </div>
                                    <ul class="pagination">
                                       {% if page_obj.has_previous %}
                                        <li class="pagination-previous-bottom">
                                        	<a href="?page=1">&laquo; first</a>
                                            <a href="?page={{ page_obj.previous_page_number }}">
                                              previous
                                            </a>
                                        </li>
                                        {% endif %}
                                        <li class="active current">
                                            <a href="shop.html">
                                                1
                                            </a>
                                        </li>
                                        <li>
                                            <a href="shop.html">
                                                2
                                            </a>
                                        </li>
                                         {% if page_obj.has_next %}	
                                        <li class="pagination-next-bottom">
                                            <a href="?page={{ page_obj.next_page_number }}">
                                                n
                                            </a>
                                            <a href="?page={{ page_obj.paginator.num_pages }}"></a>
                                        </li>
                                        {% endif %}
                                    </ul>
                                </div>
                                
                            </div>
                        </div> -->
                        {% if products.has_other_pages %}
						  <ul class="pagination">
						    {% if products.has_previous %}
						      <li><a href="?page={{ products.previous_page_number }}">&laquo;</a></li>
						    {% else %}
						      <li class="disabled"><span>&laquo;</span></li>
						    {% endif %}
						    {% for i in products.paginator.page_range %}
						      {% if products.number == i %}
						        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
						      {% else %}
						        <li><a href="?page={{ i }}">{{ i }}</a></li>
						      {% endif %}
						    {% endfor %}
						    {% if products.has_next %}
						      <li><a href="?page={{ products.next_page_number }}">&raquo;</a></li>
						    {% else %}
						      <li class="disabled"><span>&raquo;</span></li>
						    {% endif %}
						  </ul>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
		</div>
		
{% endblock %}